import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { memo } from "react";
import { useLocale } from "@/hooks/useLocale";
import { formatCompactDateTime, formatDuration, isNextDay } from "@common/utils/time";
import TripStatusBadge from "./TripStatusBadge";
function TripTable({ trips, onView, onEdit, onCancel }) {
    const { t } = useLocale();
    return (_jsx("div", { className: "card", children: _jsxs("table", { className: "table", "aria-label": t("trips.title"), children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { scope: "col", children: t("table.origin") }), _jsx("th", { scope: "col", children: t("table.destination") }), _jsx("th", { scope: "col", children: t("table.departure") }), _jsx("th", { scope: "col", children: t("table.arrival") }), _jsx("th", { scope: "col", children: t("table.status") }), _jsx("th", { scope: "col", children: t("table.duration") }), _jsx("th", { scope: "col", children: t("table.driver") }), _jsx("th", { scope: "col", children: t("table.actions") })] }) }), _jsx("tbody", { children: trips.map(trip => (_jsxs("tr", { className: "table-row-clickable", onClick: () => onView(trip.id), children: [_jsx("td", { children: trip.origin }), _jsx("td", { children: trip.destination }), _jsx("td", { className: "time-cell", children: formatCompactDateTime(trip.departureTime, trip.departureTimezone) }), _jsx("td", { className: "time-cell", children: trip.arrivalTime && trip.arrivalTimezone ? (_jsxs(_Fragment, { children: [formatCompactDateTime(trip.arrivalTime, trip.arrivalTimezone), isNextDay(trip.departureTime, trip.departureTimezone, trip.arrivalTime, trip.arrivalTimezone) && (_jsx("span", { className: "next-day", "aria-label": "next day", children: "+1" }))] })) : (_jsx("span", { className: "text-secondary", children: "\u2014" })) }), _jsx("td", { children: _jsx(TripStatusBadge, { status: trip.status }) }), _jsx("td", { className: "text-secondary", children: trip.arrivalTime ? formatDuration(trip.departureTime, trip.arrivalTime) : "—" }), _jsx("td", { children: trip.driver }), _jsx("td", { children: _jsxs("div", { className: "actions", children: [_jsx("button", { className: "btn btn-sm", "aria-label": `${t("action.view")} ${trip.origin} to ${trip.destination}`, onClick: e => { e.stopPropagation(); onView(trip.id); }, children: t("action.view") }), _jsx("button", { className: "btn btn-sm", "aria-label": `${t("action.edit")} ${trip.origin} to ${trip.destination}`, onClick: e => { e.stopPropagation(); onEdit(trip.id); }, children: t("action.edit") }), trip.status !== "cancelled" && trip.status !== "arrived" && (_jsx("button", { className: "btn btn-sm btn-danger", "aria-label": `${t("action.cancel")} ${trip.origin} to ${trip.destination}`, onClick: e => { e.stopPropagation(); onCancel(trip.id); }, children: t("action.cancel") }))] }) })] }, trip.id))) })] }) }));
}
export default memo(TripTable);
