import type { Trip } from "../models/trip";

export const SEED_TRIPS: Trip[] = [
  {
    id: 1,
    origin: "Lisbon",
    destination: "Madrid",
    departureTime: "2026-02-20T07:30:00Z",
    departureTimezone: "Europe/Lisbon",
    arrivalTimezone: "Europe/Madrid",
    status: "scheduled",
    driver: "Maria Santos",
  },
  {
    id: 2,
    origin: "Paris",
    destination: "Brussels",
    departureTime: "2026-02-20T08:00:00Z",
    departureTimezone: "Europe/Paris",
    arrivalTimezone: "Europe/Brussels",
    status: "delayed",
    driver: "Jean Dupont",
  },
  {
    id: 3,
    origin: "Berlin",
    destination: "Warsaw",
    departureTime: "2026-02-20T08:45:00Z",
    departureTimezone: "Europe/Berlin",
    arrivalTimezone: "Europe/Warsaw",
    status: "scheduled",
    driver: "Klaus Müller",
  },
  {
    id: 4,
    origin: "Amsterdam",
    destination: "London",
    departureTime: "2026-02-20T09:30:00Z",
    departureTimezone: "Europe/Amsterdam",
    arrivalTimezone: "Europe/London",
    status: "cancelled",
    driver: "Anna de Vries",
  },
  {
    id: 5,
    origin: "Rome",
    destination: "Vienna",
    departureTime: "2026-02-20T06:00:00Z",
    departureTimezone: "Europe/Rome",
    arrivalTime: "2026-02-20T10:15:00Z",
    arrivalTimezone: "Europe/Vienna",
    status: "arrived",
    driver: "Marco Rossi",
  },
  {
    id: 6,
    origin: "Madrid",
    destination: "Barcelona",
    departureTime: "2026-02-20T10:30:00Z",
    departureTimezone: "Europe/Madrid",
    arrivalTimezone: "Europe/Madrid",
    status: "scheduled",
    driver: "Carlos López",
  },
  {
    id: 7,
    origin: "Prague",
    destination: "Budapest",
    departureTime: "2026-02-20T11:00:00Z",
    departureTimezone: "Europe/Prague",
    arrivalTimezone: "Europe/Budapest",
    status: "delayed",
    driver: "Tomáš Novák",
  },
  {
    id: 8,
    origin: "Stockholm",
    destination: "Copenhagen",
    departureTime: "2026-02-20T12:00:00Z",
    departureTimezone: "Europe/Stockholm",
    arrivalTimezone: "Europe/Copenhagen",
    status: "scheduled",
    driver: "Erik Lindqvist",
  },
  {
    id: 9,
    origin: "Lisbon",
    destination: "Paris",
    departureTime: "2026-02-20T22:00:00Z",
    departureTimezone: "Europe/Lisbon",
    arrivalTimezone: "Europe/Paris",
    status: "scheduled",
    driver: "Ricardo Torres",
  },
  {
    id: 10,
    origin: "Warsaw",
    destination: "Riga",
    departureTime: "2026-02-20T14:30:00Z",
    departureTimezone: "Europe/Warsaw",
    arrivalTimezone: "Europe/Riga",
    status: "delayed",
    driver: "Piotr Kowalski",
  },
];
